### PR TITLE
Parallel download

### PR DESCRIPTION
**Pull request by jreadey**
Please take a look.  I've added a simple util app for doing the s3 downloads: s3pd.py.  Also I've cut out the downloading code from summary .py.

### CODE REVIEW

**Comment by ajelenak-thg** [comment]
Is it now required to run `lib/setup.py` to install the S3 modules?

**Comment by jreadey** [comment]
I couldn't think of a better way to make the module available.

**Comment by ajelenak-thg** [comment]
All of this is on the ipcontroller VM.

I run `python setup.py install`. From the displayed messages it seems the modules are installed in `/home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/s3downloader`. When I then try to run `ncep_summary.py` I get errors: `ImportError: No module named 's3downloader'` for both `s3pd.py` and `summary.py`.
```sh
$ ll /home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/s3downloader
total 40
drwxrwxr-x  3 ubuntu ubuntu  4096 Nov 19 17:54 ./
drwxrwxr-x 27 ubuntu ubuntu  4096 Nov 19 17:54 ../
-rw-rw-r--  1 ubuntu ubuntu   180 Nov 19 17:07 __init__.py
drwxrwxr-x  2 ubuntu ubuntu  4096 Nov 19 17:54 __pycache__/
-rw-rw-r--  1 ubuntu ubuntu 12405 Nov 19 17:07 s3downloader.py
-rw-rw-r--  1 ubuntu ubuntu  2878 Nov 19 17:07 s3paralleldownloader.py
-rw-rw-r--  1 ubuntu ubuntu   748 Nov 19 17:07 setup.py
```

**Comment by jreadey** [comment]
Are these errors from the controller vm or from the engines?
You'll need to update the ipengine snapshot for the engines to see the packages.

**Comment by ajelenak-thg** [comment]
> Are these errors from the controller vm or from the engines?

From the controller VM.

> You'll need to update the ipengine snapshot for the engines to see the packages.

I thought so. What would happen if we modified those modules? Build a new snapshot each time?

**Comment by jreadey** [comment]
Yep. :)

Can you run the downloader test cases in lib?  Can you run them without changing the python path?

**Comment by ajelenak-thg** [comment]
> Can you run the downloader test cases in lib? Can you run them without changing the python path?

Yes, they seemed to run fine. I did the `setup.py install` before.

Since we need a new snapshot to really use all this goodness let's merge. @jreadey can you add instructions on how to make a new snapshot to the tips document? I guess we'll be building snapshots more often... ;-)

**Comment by jreadey** [comment]
Ok, I've merged with master.  Next I'll try to get the snapshots sorted out!

**Pull request merged**
